/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ATM.MainMenu;

import ATM.Class.ArraysClass;
import ATM.Exit.Exit;

/**
 *
 * @author Derakhshan
 */
public class UserMainMenu extends javax.swing.JFrame {

    ArraysClass ac = new ArraysClass();
    public int lan ;

    /**
     * Creates new form UserMainMenu
     */
    public UserMainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAccountBalance = new javax.swing.JButton();
        btnWithdrawCash = new javax.swing.JButton();
        btnTransfer = new javax.swing.JButton();
        btnBill = new javax.swing.JButton();
        btnSimCardRecharge = new javax.swing.JButton();
        btnOtherServices = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnAccountBalance.setText("اعلام موجودی");
        btnAccountBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccountBalanceActionPerformed(evt);
            }
        });

        btnWithdrawCash.setText("برداشت وجه");
        btnWithdrawCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWithdrawCashActionPerformed(evt);
            }
        });

        btnTransfer.setText("انتقال وجه");
        btnTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferActionPerformed(evt);
            }
        });

        btnBill.setText("پرداخت قبوض");
        btnBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBillActionPerformed(evt);
            }
        });

        btnSimCardRecharge.setText("خرید شارژ");
        btnSimCardRecharge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimCardRechargeActionPerformed(evt);
            }
        });

        btnOtherServices.setText("سایر خدمات");
        btnOtherServices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtherServicesActionPerformed(evt);
            }
        });

        btnExit.setText("خروج");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        jLabel1.setText("منوی اصلی");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAccountBalance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnWithdrawCash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTransfer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSimCardRecharge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnOtherServices, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(109, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(94, 94, 94))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAccountBalance)
                .addGap(18, 18, 18)
                .addComponent(btnWithdrawCash)
                .addGap(18, 18, 18)
                .addComponent(btnTransfer)
                .addGap(18, 18, 18)
                .addComponent(btnSimCardRecharge)
                .addGap(18, 18, 18)
                .addComponent(btnBill)
                .addGap(18, 18, 18)
                .addComponent(btnOtherServices)
                .addGap(18, 18, 18)
                .addComponent(btnExit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        Exit e = new Exit();
        e.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnAccountBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccountBalanceActionPerformed
        AccountBalance ab = new AccountBalance();
        ab.lan = this.lan;
        ab.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAccountBalanceActionPerformed

    private void btnWithdrawCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWithdrawCashActionPerformed
        WithdrawCash wdc = new WithdrawCash();
        wdc.lan = this.lan;
        wdc.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnWithdrawCashActionPerformed

    private void btnTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferActionPerformed
        Transfer t = new Transfer();
        t.lan = this.lan;
        t.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnTransferActionPerformed

    private void btnSimCardRechargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimCardRechargeActionPerformed
        SimCardRecharge scr = new SimCardRecharge();
        scr.lan = this.lan;
        scr.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnSimCardRechargeActionPerformed

    private void btnOtherServicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtherServicesActionPerformed
        OtherServices os = new OtherServices();
        os.lan = this.lan;
        os.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnOtherServicesActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        if (lan == 0) {
            btnAccountBalance.setText("Account Balance");
            btnExit.setText("Exit");
            btnOtherServices.setText("Other services");
            btnSimCardRecharge.setText("Sim card recharge");
            btnTransfer.setText("Transfer money");
            btnWithdrawCash.setText("Witghdraw cash");
            btnBill.setText("Pay Bills");
            jLabel1.setText("Main menu");
        }
    }//GEN-LAST:event_formWindowOpened

    private void btnBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBillActionPerformed
        PayBills pb = new PayBills();
        pb.lan = this.lan;
        pb.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBillActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserMainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccountBalance;
    private javax.swing.JButton btnBill;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnOtherServices;
    private javax.swing.JButton btnSimCardRecharge;
    private javax.swing.JButton btnTransfer;
    private javax.swing.JButton btnWithdrawCash;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
