/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ATM.Admin;

import ATM.Class.ArraysClass;
import ATM.Exit.Exit;

/**
 *
 * @author Derakhshan
 */
public class AdminMainMenu extends javax.swing.JFrame {

    ArraysClass ac = new ArraysClass();
    public int lan ;

    /**
     * Creates new form AdminMainMenu
     */
    public AdminMainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAddNewAccount = new javax.swing.JButton();
        btnChangeAccountBalance = new javax.swing.JButton();
        btnChangeAccountCondition = new javax.swing.JButton();
        btnChangeUsersPassword = new javax.swing.JButton();
        btnAccounts = new javax.swing.JButton();
        btnChangeAdminsPassword = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnAddNewAccount.setText("اضافه کردن کارت");
        btnAddNewAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewAccountActionPerformed(evt);
            }
        });

        btnChangeAccountBalance.setText("تغییر موجودی کارت");
        btnChangeAccountBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeAccountBalanceActionPerformed(evt);
            }
        });

        btnChangeAccountCondition.setText("قفل / باز کردن حساب");
        btnChangeAccountCondition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeAccountConditionActionPerformed(evt);
            }
        });

        btnChangeUsersPassword.setText("تغییر رمز کارت");
        btnChangeUsersPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeUsersPasswordActionPerformed(evt);
            }
        });

        btnAccounts.setText("مشاهده حساب ها");
        btnAccounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccountsActionPerformed(evt);
            }
        });

        btnChangeAdminsPassword.setText("تغییر رمز مدیر");
        btnChangeAdminsPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeAdminsPasswordActionPerformed(evt);
            }
        });

        btnExit.setText("خروج");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnChangeUsersPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAccounts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddNewAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnChangeAccountBalance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnChangeAccountCondition, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(btnChangeAdminsPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAccounts)
                .addGap(18, 18, 18)
                .addComponent(btnAddNewAccount)
                .addGap(18, 18, 18)
                .addComponent(btnChangeAccountBalance)
                .addGap(18, 18, 18)
                .addComponent(btnChangeUsersPassword)
                .addGap(18, 18, 18)
                .addComponent(btnChangeAccountCondition)
                .addGap(18, 18, 18)
                .addComponent(btnChangeAdminsPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        Exit e = new Exit();
        e.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnAccountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccountsActionPerformed
        Accounts a = new Accounts();
        a.lan = this.lan;
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAccountsActionPerformed

    private void btnChangeAccountBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeAccountBalanceActionPerformed
        ChangeUsersAccountBalance cuab = new ChangeUsersAccountBalance();
        cuab.lan = this.lan;
        cuab.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnChangeAccountBalanceActionPerformed

    private void btnChangeUsersPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeUsersPasswordActionPerformed
        ChangeUsersPassword cup = new ChangeUsersPassword();
        cup.lan = this.lan;
        cup.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnChangeUsersPasswordActionPerformed

    private void btnAddNewAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewAccountActionPerformed
        AddNewAccount ana = new AddNewAccount();
        ana.lan = this.lan;
        ana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAddNewAccountActionPerformed

    private void btnChangeAccountConditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeAccountConditionActionPerformed
        ChangeAccountCondition cac = new ChangeAccountCondition();
        cac.lan = this.lan;
        cac.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnChangeAccountConditionActionPerformed

    private void btnChangeAdminsPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeAdminsPasswordActionPerformed
        ChangeAdminsPassword cap = new ChangeAdminsPassword();
        cap.lan = this.lan;
        cap.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnChangeAdminsPasswordActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        if (lan == 0) {
            btnAccounts.setText("Accounts");
            btnAddNewAccount.setText("Add new accounts");
            btnChangeAccountBalance.setText("Change user's account  balance");
            btnChangeAccountCondition.setText("Change user's account condition");
            btnChangeUsersPassword.setText("Change user's password");
            btnChangeAdminsPassword.setText("Change admin's password");
            btnExit.setText("Exit");
        }ac.defaultAccounts();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccounts;
    private javax.swing.JButton btnAddNewAccount;
    private javax.swing.JButton btnChangeAccountBalance;
    private javax.swing.JButton btnChangeAccountCondition;
    private javax.swing.JButton btnChangeAdminsPassword;
    private javax.swing.JButton btnChangeUsersPassword;
    private javax.swing.JButton btnExit;
    // End of variables declaration//GEN-END:variables
}
